spring:
  application:
    name: keycloak-api
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/uber-services
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak-admin:
  realm: master
  url: http://localhost:8080
  username: admin
  password: password
  client-id: admin-cli

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

jwt:
  auth:
    converter:
      resource-id: uber-app
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG


app:
  cors:
    allowed-origins: http://localhost:3000,*


server:
  port: 3333

