/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.api.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DriverCallRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3860088642540466282L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DriverCallRequestAvroModel\",\"namespace\":\"com.uber.api.kafka.model\",\"fields\":[{\"name\":\"requestId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"ipAddress\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"customerMail\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"driverMail\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"price\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"driverStatus\",\"type\":{\"type\":\"enum\",\"name\":\"DriverStatus\",\"symbols\":[\"AVAILABLE\",\"CALL\",\"UNAVAILABLE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<DriverCallRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<DriverCallRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DriverCallRequestAvroModel> DECODER =
      new BinaryMessageDecoder<DriverCallRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DriverCallRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DriverCallRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DriverCallRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DriverCallRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DriverCallRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DriverCallRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DriverCallRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DriverCallRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String requestId;
  private java.lang.String sagaId;
  private java.lang.String ipAddress;
  private java.lang.String customerMail;
  private java.lang.String driverMail;
  private java.math.BigDecimal price;
  private java.time.Instant createdAt;
  private com.uber.api.kafka.model.DriverStatus driverStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DriverCallRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param requestId The new value for requestId
   * @param sagaId The new value for sagaId
   * @param ipAddress The new value for ipAddress
   * @param customerMail The new value for customerMail
   * @param driverMail The new value for driverMail
   * @param price The new value for price
   * @param createdAt The new value for createdAt
   * @param driverStatus The new value for driverStatus
   */
  public DriverCallRequestAvroModel(java.lang.String requestId, java.lang.String sagaId, java.lang.String ipAddress, java.lang.String customerMail, java.lang.String driverMail, java.math.BigDecimal price, java.time.Instant createdAt, com.uber.api.kafka.model.DriverStatus driverStatus) {
    this.requestId = requestId;
    this.sagaId = sagaId;
    this.ipAddress = ipAddress;
    this.customerMail = customerMail;
    this.driverMail = driverMail;
    this.price = price;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.driverStatus = driverStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return sagaId;
    case 2: return ipAddress;
    case 3: return customerMail;
    case 4: return driverMail;
    case 5: return price;
    case 6: return createdAt;
    case 7: return driverStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: ipAddress = value$ != null ? value$.toString() : null; break;
    case 3: customerMail = value$ != null ? value$.toString() : null; break;
    case 4: driverMail = value$ != null ? value$.toString() : null; break;
    case 5: price = (java.math.BigDecimal)value$; break;
    case 6: createdAt = (java.time.Instant)value$; break;
    case 7: driverStatus = (com.uber.api.kafka.model.DriverStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.String getRequestId() {
    return requestId;
  }


  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.String value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'customerMail' field.
   * @return The value of the 'customerMail' field.
   */
  public java.lang.String getCustomerMail() {
    return customerMail;
  }


  /**
   * Sets the value of the 'customerMail' field.
   * @param value the value to set.
   */
  public void setCustomerMail(java.lang.String value) {
    this.customerMail = value;
  }

  /**
   * Gets the value of the 'driverMail' field.
   * @return The value of the 'driverMail' field.
   */
  public java.lang.String getDriverMail() {
    return driverMail;
  }


  /**
   * Sets the value of the 'driverMail' field.
   * @param value the value to set.
   */
  public void setDriverMail(java.lang.String value) {
    this.driverMail = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.math.BigDecimal getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.math.BigDecimal value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'driverStatus' field.
   * @return The value of the 'driverStatus' field.
   */
  public com.uber.api.kafka.model.DriverStatus getDriverStatus() {
    return driverStatus;
  }


  /**
   * Sets the value of the 'driverStatus' field.
   * @param value the value to set.
   */
  public void setDriverStatus(com.uber.api.kafka.model.DriverStatus value) {
    this.driverStatus = value;
  }

  /**
   * Creates a new DriverCallRequestAvroModel RecordBuilder.
   * @return A new DriverCallRequestAvroModel RecordBuilder
   */
  public static com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder newBuilder() {
    return new com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder();
  }

  /**
   * Creates a new DriverCallRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DriverCallRequestAvroModel RecordBuilder
   */
  public static com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder newBuilder(com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder();
    } else {
      return new com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DriverCallRequestAvroModel RecordBuilder by copying an existing DriverCallRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DriverCallRequestAvroModel RecordBuilder
   */
  public static com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder newBuilder(com.uber.api.kafka.model.DriverCallRequestAvroModel other) {
    if (other == null) {
      return new com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder();
    } else {
      return new com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DriverCallRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DriverCallRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<DriverCallRequestAvroModel> {

    private java.lang.String requestId;
    private java.lang.String sagaId;
    private java.lang.String ipAddress;
    private java.lang.String customerMail;
    private java.lang.String driverMail;
    private java.math.BigDecimal price;
    private java.time.Instant createdAt;
    private com.uber.api.kafka.model.DriverStatus driverStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[2].schema(), other.ipAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.customerMail)) {
        this.customerMail = data().deepCopy(fields()[3].schema(), other.customerMail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.driverMail)) {
        this.driverMail = data().deepCopy(fields()[4].schema(), other.driverMail);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.driverStatus)) {
        this.driverStatus = data().deepCopy(fields()[7].schema(), other.driverStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing DriverCallRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uber.api.kafka.model.DriverCallRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[2].schema(), other.ipAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customerMail)) {
        this.customerMail = data().deepCopy(fields()[3].schema(), other.customerMail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.driverMail)) {
        this.driverMail = data().deepCopy(fields()[4].schema(), other.driverMail);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.driverStatus)) {
        this.driverStatus = data().deepCopy(fields()[7].schema(), other.driverStatus);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * @return The value.
      */
    public java.lang.String getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setRequestId(java.lang.String value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setIpAddress(java.lang.String value) {
      validate(fields()[2], value);
      this.ipAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerMail' field.
      * @return The value.
      */
    public java.lang.String getCustomerMail() {
      return customerMail;
    }


    /**
      * Sets the value of the 'customerMail' field.
      * @param value The value of 'customerMail'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setCustomerMail(java.lang.String value) {
      validate(fields()[3], value);
      this.customerMail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'customerMail' field has been set.
      * @return True if the 'customerMail' field has been set, false otherwise.
      */
    public boolean hasCustomerMail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'customerMail' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearCustomerMail() {
      customerMail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverMail' field.
      * @return The value.
      */
    public java.lang.String getDriverMail() {
      return driverMail;
    }


    /**
      * Sets the value of the 'driverMail' field.
      * @param value The value of 'driverMail'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setDriverMail(java.lang.String value) {
      validate(fields()[4], value);
      this.driverMail = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'driverMail' field has been set.
      * @return True if the 'driverMail' field has been set, false otherwise.
      */
    public boolean hasDriverMail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'driverMail' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearDriverMail() {
      driverMail = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.math.BigDecimal getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setPrice(java.math.BigDecimal value) {
      validate(fields()[5], value);
      this.price = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearPrice() {
      price = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverStatus' field.
      * @return The value.
      */
    public com.uber.api.kafka.model.DriverStatus getDriverStatus() {
      return driverStatus;
    }


    /**
      * Sets the value of the 'driverStatus' field.
      * @param value The value of 'driverStatus'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder setDriverStatus(com.uber.api.kafka.model.DriverStatus value) {
      validate(fields()[7], value);
      this.driverStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'driverStatus' field has been set.
      * @return True if the 'driverStatus' field has been set, false otherwise.
      */
    public boolean hasDriverStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'driverStatus' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.DriverCallRequestAvroModel.Builder clearDriverStatus() {
      driverStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DriverCallRequestAvroModel build() {
      try {
        DriverCallRequestAvroModel record = new DriverCallRequestAvroModel();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.ipAddress = fieldSetFlags()[2] ? this.ipAddress : (java.lang.String) defaultValue(fields()[2]);
        record.customerMail = fieldSetFlags()[3] ? this.customerMail : (java.lang.String) defaultValue(fields()[3]);
        record.driverMail = fieldSetFlags()[4] ? this.driverMail : (java.lang.String) defaultValue(fields()[4]);
        record.price = fieldSetFlags()[5] ? this.price : (java.math.BigDecimal) defaultValue(fields()[5]);
        record.createdAt = fieldSetFlags()[6] ? this.createdAt : (java.time.Instant) defaultValue(fields()[6]);
        record.driverStatus = fieldSetFlags()[7] ? this.driverStatus : (com.uber.api.kafka.model.DriverStatus) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DriverCallRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DriverCallRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DriverCallRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DriverCallRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










