/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.api.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum DriverStatus implements org.apache.avro.generic.GenericEnumSymbol<DriverStatus> {
  AVAILABLE, CALL, UNAVAILABLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DriverStatus\",\"namespace\":\"com.uber.api.kafka.model\",\"symbols\":[\"AVAILABLE\",\"CALL\",\"UNAVAILABLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
