/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.api.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum PaymentCustomerStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentCustomerStatus> {
  PENDING, CANCELED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentCustomerStatus\",\"namespace\":\"com.uber.api.kafka.model\",\"symbols\":[\"PENDING\",\"CANCELED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
