/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.api.kafka.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class UserCreateRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8679462129883578299L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserCreateRequest\",\"namespace\":\"com.uber.api.kafka.model\",\"fields\":[{\"name\":\"userMail\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"userType\",\"type\":{\"type\":\"enum\",\"name\":\"UserType\",\"symbols\":[\"DRIVER\",\"CUSTOMER\"]}},{\"name\":\"openingBalance\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<UserCreateRequest> ENCODER =
      new BinaryMessageEncoder<UserCreateRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserCreateRequest> DECODER =
      new BinaryMessageDecoder<UserCreateRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserCreateRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserCreateRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserCreateRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserCreateRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserCreateRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserCreateRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserCreateRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserCreateRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String userMail;
  private com.uber.api.kafka.model.UserType userType;
  private java.math.BigDecimal openingBalance;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserCreateRequest() {}

  /**
   * All-args constructor.
   * @param userMail The new value for userMail
   * @param userType The new value for userType
   * @param openingBalance The new value for openingBalance
   * @param createdAt The new value for createdAt
   */
  public UserCreateRequest(java.lang.String userMail, com.uber.api.kafka.model.UserType userType, java.math.BigDecimal openingBalance, java.time.Instant createdAt) {
    this.userMail = userMail;
    this.userType = userType;
    this.openingBalance = openingBalance;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userMail;
    case 1: return userType;
    case 2: return openingBalance;
    case 3: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userMail = value$ != null ? value$.toString() : null; break;
    case 1: userType = (com.uber.api.kafka.model.UserType)value$; break;
    case 2: openingBalance = (java.math.BigDecimal)value$; break;
    case 3: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userMail' field.
   * @return The value of the 'userMail' field.
   */
  public java.lang.String getUserMail() {
    return userMail;
  }


  /**
   * Sets the value of the 'userMail' field.
   * @param value the value to set.
   */
  public void setUserMail(java.lang.String value) {
    this.userMail = value;
  }

  /**
   * Gets the value of the 'userType' field.
   * @return The value of the 'userType' field.
   */
  public com.uber.api.kafka.model.UserType getUserType() {
    return userType;
  }


  /**
   * Sets the value of the 'userType' field.
   * @param value the value to set.
   */
  public void setUserType(com.uber.api.kafka.model.UserType value) {
    this.userType = value;
  }

  /**
   * Gets the value of the 'openingBalance' field.
   * @return The value of the 'openingBalance' field.
   */
  public java.math.BigDecimal getOpeningBalance() {
    return openingBalance;
  }


  /**
   * Sets the value of the 'openingBalance' field.
   * @param value the value to set.
   */
  public void setOpeningBalance(java.math.BigDecimal value) {
    this.openingBalance = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new UserCreateRequest RecordBuilder.
   * @return A new UserCreateRequest RecordBuilder
   */
  public static com.uber.api.kafka.model.UserCreateRequest.Builder newBuilder() {
    return new com.uber.api.kafka.model.UserCreateRequest.Builder();
  }

  /**
   * Creates a new UserCreateRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserCreateRequest RecordBuilder
   */
  public static com.uber.api.kafka.model.UserCreateRequest.Builder newBuilder(com.uber.api.kafka.model.UserCreateRequest.Builder other) {
    if (other == null) {
      return new com.uber.api.kafka.model.UserCreateRequest.Builder();
    } else {
      return new com.uber.api.kafka.model.UserCreateRequest.Builder(other);
    }
  }

  /**
   * Creates a new UserCreateRequest RecordBuilder by copying an existing UserCreateRequest instance.
   * @param other The existing instance to copy.
   * @return A new UserCreateRequest RecordBuilder
   */
  public static com.uber.api.kafka.model.UserCreateRequest.Builder newBuilder(com.uber.api.kafka.model.UserCreateRequest other) {
    if (other == null) {
      return new com.uber.api.kafka.model.UserCreateRequest.Builder();
    } else {
      return new com.uber.api.kafka.model.UserCreateRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserCreateRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserCreateRequest>
    implements org.apache.avro.data.RecordBuilder<UserCreateRequest> {

    private java.lang.String userMail;
    private com.uber.api.kafka.model.UserType userType;
    private java.math.BigDecimal openingBalance;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uber.api.kafka.model.UserCreateRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userMail)) {
        this.userMail = data().deepCopy(fields()[0].schema(), other.userMail);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userType)) {
        this.userType = data().deepCopy(fields()[1].schema(), other.userType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.openingBalance)) {
        this.openingBalance = data().deepCopy(fields()[2].schema(), other.openingBalance);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing UserCreateRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uber.api.kafka.model.UserCreateRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userMail)) {
        this.userMail = data().deepCopy(fields()[0].schema(), other.userMail);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userType)) {
        this.userType = data().deepCopy(fields()[1].schema(), other.userType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.openingBalance)) {
        this.openingBalance = data().deepCopy(fields()[2].schema(), other.openingBalance);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'userMail' field.
      * @return The value.
      */
    public java.lang.String getUserMail() {
      return userMail;
    }


    /**
      * Sets the value of the 'userMail' field.
      * @param value The value of 'userMail'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder setUserMail(java.lang.String value) {
      validate(fields()[0], value);
      this.userMail = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userMail' field has been set.
      * @return True if the 'userMail' field has been set, false otherwise.
      */
    public boolean hasUserMail() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userMail' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder clearUserMail() {
      userMail = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userType' field.
      * @return The value.
      */
    public com.uber.api.kafka.model.UserType getUserType() {
      return userType;
    }


    /**
      * Sets the value of the 'userType' field.
      * @param value The value of 'userType'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder setUserType(com.uber.api.kafka.model.UserType value) {
      validate(fields()[1], value);
      this.userType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userType' field has been set.
      * @return True if the 'userType' field has been set, false otherwise.
      */
    public boolean hasUserType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userType' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder clearUserType() {
      userType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'openingBalance' field.
      * @return The value.
      */
    public java.math.BigDecimal getOpeningBalance() {
      return openingBalance;
    }


    /**
      * Sets the value of the 'openingBalance' field.
      * @param value The value of 'openingBalance'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder setOpeningBalance(java.math.BigDecimal value) {
      validate(fields()[2], value);
      this.openingBalance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'openingBalance' field has been set.
      * @return True if the 'openingBalance' field has been set, false otherwise.
      */
    public boolean hasOpeningBalance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'openingBalance' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder clearOpeningBalance() {
      openingBalance = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[3], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.uber.api.kafka.model.UserCreateRequest.Builder clearCreatedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserCreateRequest build() {
      try {
        UserCreateRequest record = new UserCreateRequest();
        record.userMail = fieldSetFlags()[0] ? this.userMail : (java.lang.String) defaultValue(fields()[0]);
        record.userType = fieldSetFlags()[1] ? this.userType : (com.uber.api.kafka.model.UserType) defaultValue(fields()[1]);
        record.openingBalance = fieldSetFlags()[2] ? this.openingBalance : (java.math.BigDecimal) defaultValue(fields()[2]);
        record.createdAt = fieldSetFlags()[3] ? this.createdAt : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserCreateRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserCreateRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserCreateRequest>
    READER$ = (org.apache.avro.io.DatumReader<UserCreateRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










