/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.api.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum UserType implements org.apache.avro.generic.GenericEnumSymbol<UserType> {
  DRIVER, CUSTOMER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserType\",\"namespace\":\"com.uber.api.kafka.model\",\"symbols\":[\"DRIVER\",\"CUSTOMER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
